name: Publish on crates.io

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: crates-io-${{ github.event.release.tag_name || github.run_id }}
  cancel-in-progress: false

jobs:
  publish-crates-io:
    name: Publish root crate
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install system dependencies
        uses: ./.github/actions/install-linux-deps
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Publish
        run: cargo publish --locked --token ${{ secrets.CARGO_TOKEN }}
